name: test_app
description: Test Flutter app.
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.3
  font_awesome_flutter: ^8.8.1
  carousel_slider: ^2.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  

  assets:
    - assets/images/1-1.jpg
    - assets/images/1-2.jpg
    - assets/images/1-3.jpg
    - assets/images/1-4.jpg
    - assets/images/frida.jpg
    - assets/images/graciela1.jpg
    - assets/images/carousel_1.jpg
    - assets/images/carousel_2.jpg
    - assets/images/carousel_3.jpg
    - assets/images/carousel_4.jpg
    - assets/images/carousel_5.jpg
    - assets/images/granny.jpg
    - assets/images/laptop.jpg
    - assets/images/people.jpg
    - assets/images/cali_1.jpg
    - assets/images/cali_2.jpg
    - assets/images/jesi_1.jpg
    - assets/images/jesi_2.jpg
    - assets/images/jesi_3.jpg
    - assets/images/5-1-1.png
    - assets/images/5-1-2.png
    - assets/images/5-2-1.png
    - assets/images/5-2-2.png
    - assets/images/5-3-1.png
    - assets/images/5-3-2.png
    - assets/images/5-4-1.png
    - assets/images/5-4-2.png
    - assets/images/nabilla.png
