name: test_app
description: Test Flutter app.
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.3
  font_awesome_flutter: ^8.8.1
  carousel_slider: ^2.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  

  assets:
    - assets/images/graciela1.jpg
    - assets/images/carousel_1.jpg
    - assets/images/carousel_2.jpg
    - assets/images/carousel_3.jpg
    - assets/images/carousel_4.jpg
    - assets/images/carousel_5.jpg
    - assets/images/granny.jpg
    - assets/images/laptop.jpg
    - assets/images/people.jpg
    - assets/images/cali_1.jpg
    - assets/images/cali_2.jpg
    - assets/images/jesi_1.jpg
    - assets/images/jesi_2.jpg
    - assets/images/jesi_3.jpg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
